### ISSUE TITLE
ANSI - UTF_8

### ISSUE THREAD

**Issue by heraldo1980** [JoshuaMKW/SMS-Message-Editor#1]
Friend, I'm translating the 3D all stars version of Mario Sunshine, the text at the end is in ANSI, full of encodings, could you write a version with text output in UTF-8 or vice versa? because the words that contain accents in my line are all encoded in the game, and I wanted to know if you are interested in making a tool for Mario 64 from 3D all stars, to date no one has ever done it.

**Comment by JoshuaMKW** [comment]
Sorry, I don't have access to assets from 3D All Stars, and it would be illegal for you to provide them to me, so on that basis I can't reliably provide support for this and I won't accordingly. As for your question regarding SM64 from 3D All Stars, I'm not interested in that, sorry.
